manifest:
  remotes:
    - name: FearlessSpiff
      url-base: https://github.com/FearlessSpiff
  projects:
    - name: zmk
      remote: FearlessSpiff
      revision: main
      import: app/west.yml
  self:
    path: config