manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/FearlessSpiff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: cirque-trackpad-1116
      import: app/west.yml
  self:
    path: config
